### ISSUE TITLE
Different Accent for Directory Window

### ISSUE THREAD

**Issue by pleasega** [equinusocio/vsc-material-theme#63] opened 2017-07-12 18:39 UTC
I think it would be better to have a darker accent for the directory window so that it is distinguishable from the other windows.

![image](https://user-images.githubusercontent.com/20602373/28134099-83faff08-6774-11e7-8684-0117731d4798.png)

For the tabs as well

![image](https://user-images.githubusercontent.com/20602373/28150285-38151d42-67c6-11e7-8a74-533f38d35a8c.png)

Helps to know where the windows start (editor and the menu), similar to default themes.

**Comment by equinusocio** [comment] 2017-07-13 06:58
Duplicate of #43

**Closed by equinusocio** 2017-07-13 06:58 UTC
