### ISSUE TITLE
Bug: Wrong gutter indicator for add line

### ISSUE THREAD

**Issue by rejonpardenilla** [equinusocio/vsc-material-theme#89] opened 2017-09-08 16:25 UTC
When I add a new line the indicator turns red for new lines.

Palenight:

<img width="512" alt="screen shot 2017-09-08 at 11 21 39 am" src="https://user-images.githubusercontent.com/22482675/30221195-f12cea06-9487-11e7-9e45-6ba28be246fe.png">

Darker:

<img width="522" alt="screen shot 2017-09-08 at 11 22 50 am" src="https://user-images.githubusercontent.com/22482675/30221227-1edc540a-9488-11e7-8414-576388f4e079.png">

Default (no extention):

<img width="519" alt="screen shot 2017-09-08 at 11 24 16 am" src="https://user-images.githubusercontent.com/22482675/30221282-480a54c6-9488-11e7-94c5-e8fcd6979653.png">

**Comment by Zx-EvM** [comment] 2017-09-08 16:45
https://github.com/equinusocio/vsc-material-theme/issues/79

**Comment by Zx-EvM** [comment] 2017-09-08 17:21
Related issue: https://github.com/equinusocio/vsc-material-theme/issues/79

Seems this fixed in this commit: https://github.com/equinusocio/vsc-material-theme/commit/6cf67bec7c429ce696e5af579347b472f7234f46

Waiting for next release.

**Comment by Zx-EvM** [comment] 2017-09-08 17:21
Related issue: https://github.com/equinusocio/vsc-material-theme/issues/79

Seems this fixed in this commit: https://github.com/equinusocio/vsc-material-theme/commit/6cf67bec7c429ce696e5af579347b472f7234f46

Waiting for next release.

**Comment by Zx-EvM** [comment] 2017-09-08 17:21
Related issue: https://github.com/equinusocio/vsc-material-theme/issues/79

Seems this fixed in this commit: https://github.com/equinusocio/vsc-material-theme/commit/6cf67bec7c429ce696e5af579347b472f7234f46

Waiting for next release.

**Comment by Zx-EvM** [comment] 2017-09-08 17:22
Related issue: https://github.com/equinusocio/vsc-material-theme/issues/79

Seems this fixed in this commit: https://github.com/equinusocio/vsc-material-theme/commit/6cf67bec7c429ce696e5af579347b472f7234f46

Waiting for next release.

**Comment by rejonpardenilla** [comment] 2017-09-08 17:39
Thanks!

**Comment by Zx-EvM** [comment] 2017-09-08 18:03
@rejonpardenilla Seems like this issue present since VSCode 1.16.0. In my issue was present issue only for modified lines. Can you reopen this issue?

**Comment by rejonpardenilla** [comment] 2017-09-08 18:10
@Zx-EvM Yes, my vscode version is 1.16.0. Could you reproduce this bug?

**Comment by Zx-EvM** [comment] 2017-09-08 18:11
@rejonpardenilla yes. I just now reproduced this bug in VSCode 1.16.0

**Comment by equinusocio** [comment] 2017-09-11 12:32
Fixed by https://github.com/equinusocio/vsc-material-theme/commit/a605ec99e8ceb5ad228e937c6fe02e8173edd972

**Closed** 2017-09-11 12:32 UTC
