### ISSUE TITLE
Disappeared Palenight in 1.0.2

### ISSUE THREAD

**Issue by Zx-EvM** [equinusocio/vsc-material-theme#75] opened 2017-07-25 13:42 UTC
Windows 10 Version 1703 Build 15063.483
VSCode 1.14.2

Theme is unknown or not installed

![25-07-2017 06-40-17](https://user-images.githubusercontent.com/20873402/28574984-6cdc580a-7104-11e7-8ed5-6a15b0855d73.png)

![25-07-2017 06-40-43](https://user-images.githubusercontent.com/20873402/28574974-5ef95206-7104-11e7-8559-a472e496adce.png)

**Comment by foreggs** [comment] 2017-07-25 14:28
Same Here.

**Comment by foreggs** [comment] 2017-07-25 14:31
1. Press ctrl+shift+p
2. Type "material theme: Settings"
3. Press enter
4. select change color variant
5. select palenight.

**Comment by OctoD** [comment] 2017-07-25 14:38
@foreggs unfortunately, at this moment it seems to be the only way to update the theme variant with the correct icon set. I will dig the vsc source more again to find a better solution.

**Comment by equinusocio** [comment] 2017-07-25 14:39
@foreggs This is not a bug. Changing the theme variant require a reload because each variant use his own color for folder icons in the tree.

**Comment by foreggs** [comment] 2017-07-25 14:39
@OctoD Thanks for the quick feedback, I think you can close the issue now.

**Closed** 2017-07-25 14:39 UTC
