### ISSUE TITLE
Wrong color for camel cased constants

### ISSUE THREAD

**Issue by TitasGailius** [equinusocio/vsc-material-theme#138] opened 2018-02-10 11:28 UTC
Hello,

I came across this strange bug in PHP.
Camel cased constants have a different colour than regular constants.

<img width="222" alt="screen shot 2018-02-10 at 13 19 53" src="https://user-images.githubusercontent.com/12625773/36061666-21a5117e-0e66-11e8-9691-9c48ee1f0199.png">

- VSCode version: 1.2.0
- Extensions: All disabled except for the latest Material Theme version
- Settings: All set to default

It's ok with other colour themes so it can't be expected behaviour. Any ideas?

**Comment by equinusocio** [comment] 2018-02-10 17:43
I will investigate. Right now i have no idea about the cause.

**Comment by equinusocio** [comment] 2018-02-11 11:43
Hi @TitasGailius I found a little bug (i think) in the php extension. It provide a different scopes:

The first one is recognised as support class
<img width="376" alt="screen shot 2018-02-11 at 12 41 18" src="https://user-images.githubusercontent.com/10454741/36072956-e44e2e78-0f28-11e8-99f1-0ba4afa448af.png">

The second one is recognised as "other constant"
<img width="249" alt="screen shot 2018-02-11 at 12 41 24" src="https://user-images.githubusercontent.com/10454741/36072957-e65e7c5e-0f28-11e8-9269-cd7820e1d899.png">

I can only set the color for "other.constant" scopes, but this will afflict all the other variables.

**Comment by TitasGailius** [comment] 2018-02-15 10:25
I see developers use these scopes for PHP classes, do you think it might be a solution?

```
{
    "name": "Library class/type",
    "scope": [
        "support.type",
        "support.class"
    ],
    "settings": {
        "foreground": "#FFCB6B"
    }
},
{
    "name": "User-defined constant",
    "scope": [
        "constant.character",
        "constant.other"
    ],
    "settings": {
        "foreground": "#FFCB6B"
    }
},
```

**Comment by equinusocio** [comment] 2018-02-15 10:28
The issue is that i have two completely different scopes. I can't make the camelcase one yellow, because use the same scope of other variables. I can only make grayish the not camelcase one.

**Comment by TitasGailius** [comment] 2018-02-15 10:55
Yeah, making it grey-ish is a solution and maybe it's even a better one because it makes it easier to differentiate classes from constants although that's not how most themes that I've used behave.

For my personal liking, I wanted it to be consistent so I added this override to my vs-code config which perfectly solves the issue:
```
    "editor.tokenColorCustomizations": {
        "textMateRules":[
            {
                "scope": "constant.other.php",
                "settings": {
                    "foreground": "#FFCB6B"
                }
            }
        ]
    }
```

**Comment by equinusocio** [comment] 2018-02-15 10:59
@TitasGailius In your config you are changing the color of the second one, not the first one.

**Comment by TitasGailius** [comment] 2018-02-15 11:02
Yes, I know.
What I meant is that from my experience on how other themes behave and for my personal liking I wanted it to be yellow as it's more consistent. :)

**Comment by equinusocio** [comment] 2018-02-15 17:02
Ok, I think I can release a fix with yellow `constant.other.php`.

**Comment by equinusocio** [comment] 2018-02-19 20:50
Fixed in the new release

**Closed** 2018-02-19 21:17 UTC
Labels: Enhancement, Scheme
