### ISSUE TITLE
Comments on dark theme are almost unreadable

### ISSUE THREAD

**Issue by eliashdezr** [equinusocio/vsc-material-theme#11] opened 2017-03-02 20:49 UTC
![example](https://i.imgur.com/0A1gxyh.png)

**Comment by wprater** [comment] 2017-03-02 20:54
this is a duplicate of https://github.com/equinusocio/vsc-material-theme/issues/7 and I also commented on this https://github.com/equinusocio/vsc-material-theme/commit/262097fb7fe71ec64a4d51a2672d3089095973dd#commitcomment-20884033

it's why I cannot use this theme any longer.  Im waiting to see if Pale Night will improve legibility, since its been stated no changes will be made to this theme's colors.

**Comment by wprater** [comment] 2017-03-02 20:55
Material Ocean does a nice job making comments legible on dark theme

![image](https://cloud.githubusercontent.com/assets/10452/23526588/77c535b8-ff47-11e6-933e-b4970c3bc8c2.png)

**Comment by eliashdezr** [comment] 2017-03-02 20:56
@wprater 
Indeed, that comment on bold and lighter gray looks pretty nice.

**Comment by equinusocio** [comment] 2017-03-03 08:07
Duplicated of #7, If you want to use Material Theme you can customise your comments color. ATM no color scheme changes are planned.

**Closed by equinusocio** 2017-03-03 08:07 UTC
